main:
  - name: Situs Utama
    identifier: mainsite
    weight: 100
    params:
      header: Situs utama www.ditatompel.com.
      icon:
        vendor: font-awesome-solid
        name: globe

  - name: www.ditatompel.com
    parent: mainsite
    url: https://www.ditatompel.com
    weight: 1
    params:
      icon:
        vendor: fas
        name: globe
        className: text-primary
      description: Situs utama dari ditatompel.com.

  - identifier: mainsite-divider
    parent: mainsite
    weight: 10
    params:
      divider: true

  - name: Tools
    parent: mainsite
    url: https://www.ditatompel.com/tools
    weight: 11
    params:
      icon:
        vendor: fas
        name: wrench
      description: Koleksi tools online gratis.

  - name: Proxy Gratis
    parent: mainsite
    url: https://www.ditatompel.com/proxy
    weight: 12
    params:
      icon:
        vendor: font-awesome-solid
        name: network-wired
        color: green
      description: HTTP, HTTPS, SOCKS5 proxy list gratis.
  - name: Monero
    parent: mainsite
    url: https://www.ditatompel.com/monero
    weight: 13
    params:
      icon:
        vendor: fab
        name: monero
        color: orange
      description: Monero remote nodes.
