main:
  - name: Main Website
    identifier: mainsite
    weight: 100
    url: https://www.ditatompel.com
    params:
      header: Main site www.ditatompel.com.
      icon:
        vendor: font-awesome-solid
        name: globe

  - name: www.ditatompel.com
    parent: mainsite
    url: https://www.ditatompel.com
    weight: 1
    params:
      icon:
        vendor: fas
        name: globe
        className: text-primary
      description: Main site of ditatompel.com.

  - identifier: mainsite-divider
    parent: mainsite
    weight: 10
    params:
      divider: true

  - name: Tools
    parent: mainsite
    url: https://www.ditatompel.com/tools
    weight: 11
    params:
      icon:
        vendor: fas
        name: wrench
      description: Collection of free online tools.

  - name: Free Proxy
    parent: mainsite
    url: https://www.ditatompel.com/proxy
    weight: 12
    params:
      icon:
        vendor: font-awesome-solid
        name: network-wired
        color: green
      description: Free HTTP, HTTPS, SOCKS5 proxy list.
  - name: Monero
    parent: mainsite
    url: https://www.ditatompel.com/monero
    weight: 13
    params:
      icon:
        vendor: fab
        name: monero
        color: orange
      description: Monero remote nodes.
  - name: CVEs
    parent: mainsite
    url: https://www.ditatompel.com/cve
    weight: 14
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Publicly known CVE database.

  